require("elalitte.lazy")
require("elalitte.remap")
require("elalitte.options")
require("elalitte.plugins.telescope")
require("elalitte.plugins.nvimtree")
require("elalitte.plugins.bufferline")
-- require("elalitte.plugins.gruvbox")
require("elalitte.plugins.tokyonight")
require("elalitte.plugins.lsp")
