matches:
  ## Dev
  # HTML
  - trigger: ":div"
    replace: '<div>$|$</div>'
  - trigger: ":cla"
    replace: 'class=""'
  - trigger: ":tab"
    replace: |
      <table>
        <thead>
          <tr>
            <th><th>
            <th><th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><th>
            <td><td>
          </tr>
          <tr>
            <th><th>
            <td><td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <th><th>
            <th><th>
          </tr>
        <tfoot>
      </table>
  - trigger: ":doc"
    replace: |
      <!doctype html>
      <html lang="fr">
      <head>
        <meta charset="utf-8">
        <title>Title</title>
        <link rel="stylesheet" href="style.css">
        <script src="script.js"></script>
      </head>
      <body>
        ...
        ...
      </body>
      </html>
  # PHP
  - trigger: ":pfun"
    replace: |
      function myFunction() {
        ...
      }
  - trigger: ":pfor"
    replace: |
      for ( $i = 0; $i<count($xxx); $i++) {
        ...
      }
  - trigger: ":pif"
    replace: |
      if ( cond ) {
        ...
      }
  - trigger: ":pie"
    replace: |
      if ( cond ) {
        ...
      } else {
        ...
      }
